# Generated by Django 4.2.16 on 2024-10-29 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_blog_options_alter_blog_posted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date'], 'verbose_name': 'Комментарии к статьям блога', 'verbose_name_plural': 'Комментарии к статьям блога'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 10, 29, 13, 49, 36, 175285), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 10, 29, 13, 49, 36, 176268), verbose_name='Дата комментария'),
        ),
        migrations.AlterModelTable(
            name='comment',
            table='Comment',
        ),
    ]
